# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\assets\ui\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalcBMI(object):
    def setupUi(self, CalcBMI):
        CalcBMI.setObjectName("CalcBMI")
        CalcBMI.resize(490, 257)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CalcBMI.sizePolicy().hasHeightForWidth())
        CalcBMI.setSizePolicy(sizePolicy)
        CalcBMI.setMinimumSize(QtCore.QSize(0, 0))
        CalcBMI.setMaximumSize(QtCore.QSize(16777215, 423424))
        self.centralwidget = QtWidgets.QWidget(CalcBMI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.lang_label = QtWidgets.QLabel(self.centralwidget)
        self.lang_label.setObjectName("lang_label")
        self.horizontalLayout_4.addWidget(self.lang_label)
        self.chooseLang_box = QtWidgets.QComboBox(self.centralwidget)
        self.chooseLang_box.setObjectName("chooseLang_box")
        self.chooseLang_box.addItem("")
        self.chooseLang_box.addItem("")
        self.horizontalLayout_4.addWidget(self.chooseLang_box)
        self.reset_btn = QtWidgets.QPushButton(self.centralwidget)
        self.reset_btn.setObjectName("reset_btn")
        self.horizontalLayout_4.addWidget(self.reset_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(
            self.header, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.weight_label = QtWidgets.QLabel(self.centralwidget)
        self.weight_label.setObjectName("weight_label")
        self.verticalLayout_2.addWidget(self.weight_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weight_input = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.weight_input.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons)
        self.weight_input.setLocale(QtCore.QLocale("en_us"))
        self.weight_input.setDecimals(1)
        self.weight_input.setMaximum(999.9)
        self.weight_input.setObjectName("weight_input")
        self.horizontalLayout.addWidget(self.weight_input)
        self.kg_label = QtWidgets.QLabel(self.centralwidget)
        self.kg_label.setObjectName("kg_label")
        self.horizontalLayout.addWidget(self.kg_label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            468, 38, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.growth_label = QtWidgets.QLabel(self.centralwidget)
        self.growth_label.setObjectName("growth_label")
        self.verticalLayout_3.addWidget(self.growth_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.growth_input = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.growth_input.setLocale(QtCore.QLocale("en_us"))
        self.growth_input.setButtonSymbols(
            QtWidgets.QAbstractSpinBox.NoButtons)
        self.growth_input.setDecimals(1)
        self.growth_input.setMaximum(999.9)
        self.growth_input.setObjectName("growth_input")
        self.horizontalLayout_2.addWidget(self.growth_input)
        self.cm_label = QtWidgets.QLabel(self.centralwidget)
        self.cm_label.setObjectName("cm_label")
        self.horizontalLayout_2.addWidget(self.cm_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.calc_btn = QtWidgets.QPushButton(self.centralwidget)
        self.calc_btn.setObjectName("calc_btn")
        self.verticalLayout_5.addWidget(self.calc_btn)
        self.yourBMI_label = QtWidgets.QLabel(self.centralwidget)
        self.yourBMI_label.setObjectName("yourBMI_label")
        self.verticalLayout_5.addWidget(self.yourBMI_label)
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setObjectName("result_label")
        self.verticalLayout_5.addWidget(self.result_label)
        CalcBMI.setCentralWidget(self.centralwidget)

        self.retranslateUi(CalcBMI)
        QtCore.QMetaObject.connectSlotsByName(CalcBMI)

    def retranslateUi(self, CalcBMI):
        _translate = QtCore.QCoreApplication.translate
        CalcBMI.setWindowTitle(_translate("CalcBMI", "MainWindow"))
        self.lang_label.setText(_translate("CalcBMI", "Язык"))
        self.chooseLang_box.setItemText(0, _translate("CalcBMI", "Русский"))
        self.chooseLang_box.setItemText(1, _translate("CalcBMI", "Английский"))
        self.reset_btn.setText(_translate("CalcBMI", "Сброс"))
        self.header.setText(_translate(
            "CalcBMI", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Расчет индекса массы тела</span></p></body></html>"))
        self.weight_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p><span style=\" font-size:14pt;\">Вес в килограммах</span></p></body></html>"))
        self.kg_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p><span style=\" font-size:12pt;\">кг</span></p></body></html>"))
        self.growth_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p><span style=\" font-size:14pt;\">Рост в сантиметрах</span></p></body></html>"))
        self.cm_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p><span style=\" font-size:12pt;\">см</span></p></body></html>"))
        self.calc_btn.setText(_translate("CalcBMI", "Рассчитать"))
        self.yourBMI_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Ваш индекс массы тела:</span></p></body></html>"))
        self.result_label.setText(_translate(
            "CalcBMI", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">-</span></p></body></html>"))
